//
// Generated file, do not edit! Created by opp_msgtool 6.0 from CQImsg.msg.
//

#ifndef __PECSN_PROJECT_CQIMSG_M_H
#define __PECSN_PROJECT_CQIMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace pecsn_project {

class CQImsg;

}  // namespace pecsn_project


namespace pecsn_project {

/**
 * Class generated from <tt>CQImsg.msg:21</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CQImsg
 * {
 *     int newCQI;
 * 
 * 
 * }
 * </pre>
 */
class CQImsg : public ::omnetpp::cPacket
{
  protected:
    int newCQI = 0;

  private:
    void copy(const CQImsg& other);

  protected:
    bool operator==(const CQImsg&) = delete;

  public:
    CQImsg(const char *name=nullptr, short kind=0);
    CQImsg(const CQImsg& other);
    virtual ~CQImsg();
    CQImsg& operator=(const CQImsg& other);
    virtual CQImsg *dup() const override {return new CQImsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getNewCQI() const;
    virtual void setNewCQI(int newCQI);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CQImsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CQImsg& obj) {obj.parsimUnpack(b);}


}  // namespace pecsn_project


namespace omnetpp {

template<> inline pecsn_project::CQImsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<pecsn_project::CQImsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PECSN_PROJECT_CQIMSG_M_H

