//
// Generated file, do not edit! Created by opp_msgtool 6.0 from Packet.msg.
//

#ifndef __PECSN_PROJECT_PACKET_M_H
#define __PECSN_PROJECT_PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace pecsn_project {

class Packet;

}  // namespace pecsn_project


namespace pecsn_project {

/**
 * Class generated from <tt>Packet.msg:6</tt> by opp_msgtool.
 * <pre>
 * packet Packet
 * {
 *     int destination;
 *     int length;
 *     simtime_t arrivalTime; //same as time of generation
 * }
 * </pre>
 */
class Packet : public ::omnetpp::cPacket
{
  protected:
    int destination = 0;
    int length = 0;
    ::omnetpp::simtime_t arrivalTime = SIMTIME_ZERO;

  private:
    void copy(const Packet& other);

  protected:
    bool operator==(const Packet&) = delete;

  public:
    Packet(const char *name=nullptr, short kind=0);
    Packet(const Packet& other);
    virtual ~Packet();
    Packet& operator=(const Packet& other);
    virtual Packet *dup() const override {return new Packet(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getDestination() const;
    virtual void setDestination(int destination);

    virtual int getLength() const;
    virtual void setLength(int length);

    virtual ::omnetpp::simtime_t getArrivalTime() const;
    virtual void setArrivalTime(::omnetpp::simtime_t arrivalTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Packet& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Packet& obj) {obj.parsimUnpack(b);}


}  // namespace pecsn_project


namespace omnetpp {

template<> inline pecsn_project::Packet *fromAnyPtr(any_ptr ptr) { return check_and_cast<pecsn_project::Packet*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PECSN_PROJECT_PACKET_M_H

